### ISSUE TITLE
[CRASH] occultism & minecolonies crash on world gen

### ISSUE THREAD

**Issue by DanMeadWasTaken** [klikli-dev/occultism#1112] opened 2024-04-17 23:36 UTC
**Describe the bug**
crash on world generation when both occultism 1.125.0 & minecolonies-1.20.1-1.1.561-BETA are present

**To Reproduce**
1. create new world with both mods present

**Expected behavior**
not crashing lol.

**System (please complete the following information):**
- Occultism Version: 1.125.0
- OS: SteamOS
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
 +curios api 5.8.1
 +Domum Ornamentum-1.20.1-1.0.184-BETA
 +geckolib4 4.4.4
 +minecolonies-1.20.1-1.1.561-BETA
 +modonomicon 1.69.0
 +occultism 1.125.0
 +smartbrainlib 1.13
 +structurize-1.20.1-1.0.725-BETA
 +blockui -1.20.1-1.0.151-BETA

**Additional context**
https://mclo.gs/9JoQl2r

**Comment by klikli-dev** [comment] 2024-04-18 05:53
The crash is due to the wrong variant of SmartBrainLib being used.
There is a version for Neoforge and one for Forge, Curseforge launcher sometimes picks the wrong one. Make sure to use the one for your mod loader and this crash will not happen any more.

This is a duplicate of #1029, see also https://github.com/Tslat/SmartBrainLib/issues/57#issuecomment-1891803412 for comments of SBL's author.

**Closed as completed by klikli-dev** 2024-04-18 05:53 UTC
Labels: bug

**Comment by DanMeadWasTaken** [comment] 2024-04-18 23:07
Ahhhhhh, alright, I'll test this later once I'm at my pc again. Tysm, I only searched for Minecolonies didn't think to check the smart brain library version.
