### ISSUE TITLE
Foliot Crusher Crash

### ISSUE THREAD

**Issue by NeoFalcon1605** [klikli-dev/occultism#1032] opened 2024-01-17 17:28 UTC
**Describe the bug**
Summoning foliot crusher crashes game

**To Reproduce**
1. Perform ritual to summon foliot crusher
2. Wait for ritual to finish
3. Crash

**Expected behavior**
The foliot crusher to summon without the game crashing

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.104.1
- OS: Windows 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 
SmartBrainLib 1.13
Modonomicon 1.54.4
Curios 5.4.7
Geckolib 4.4
**Additional context**
Using NeoForge 47.1.79
Crash report: https://hastebin.com/share/ikeqanawij.perl
Latest log during crash: https://hastebin.com/share/axikutedah.csharp

**Comment by Kevin-Marsh** [comment] 2024-01-19 05:02
Forge version of smartbrain lib used on neoforge does this. Change your smartbrain lib.

**Comment by klikli-dev** [comment] 2024-01-21 09:44
Closed as duplicate of https://github.com/klikli-dev/occultism/issues/1029

**Closed as completed by klikli-dev** 2024-01-21 09:44 UTC
Labels: bug, duplicate
