### ISSUE TITLE
[BUG]: Placed a wormhole into storage, now all the items are gone?

### ISSUE THREAD

**Issue by Syogren** [klikli-dev/occultism#888] opened 2023-02-01 06:15 UTC
### Bug Description

Placing a stable wormhole of one ID into the storage of another ID appears to clear the former's item storage.  We did not try to do this on purpose, I think we just accidentally picked up a wormhole and absentmindedly threw it in storage.  This happened with the Battle Chicken Modpack, if that helps.

### Logs and Crash Reports

We do not have a log.

### Bug Reproduction

1: Create two different dimensional storage actuators
2: Fill them both with various items
3: Create a stable wormhole for one of the dimensional storages
4. Place that wormhole on the ground, then pick it back up
5. Place that wormhole in the other dimensional storage 

### Expected Behavior

The items from the first dimensional storage should disappear.

### Minecraft Version

1.18.2

### Mod Version

1.64.0

### Modpack

Other

**Comment by klikli-dev** [comment] 2023-02-01 06:50
that is a very weird bug, as the storage system does not treat the wormhole special, or tries to access its connected storage, much less clear it. 

Does this reproduce with just (latest) occultism + dependencies outside of that modpack?

**Comment by klikli-dev** [comment] 2023-02-01 06:59
@Syogren this does not reproduce on the latest version of 1.18.2 when using just occultism. 
Can you please test if 
a) this consistently reproduces on your version and 
b) if it happens for you if you install just (latest) occultism via curseforge launcher (or other launcher that installs dependencies for you)


I will close the issue meanwhile as it looks like it is not existent on the latest version, but feel free to ping me here if it does reproduce for you and I will reopen

**Closed as completed by klikli-dev** 2023-02-01 06:59 UTC
Labels: bug
