### ISSUE TITLE
Familiar ring does not release familiars on 1.16

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/occultism#605] opened 2021-12-23 08:25 UTC
Seems to be a different issue from https://github.com/klikli-dev/occultism/issues/594, the fix for 1.18 did not prevent it on 1.16

**Comment by Shibva** [comment] 2021-12-23 09:50
hey, uh, idk the context, but it seems on my end that I can release familuars, or at least I recall that recenly, dont have one on me at the moment, so cant confirm if it broke on an update or something on 1.16

**Comment by xCalvin2025x** [comment] 2021-12-25 17:40
Sorry, but I still can't release it in 1.16
I'm not sure if it's my problem ...... QAQ

**Comment by Shibva** [comment] 2021-12-25 17:41
Does the soul gem work?

**Comment by klikli-dev** [comment] 2021-12-25 20:54
> Sorry, but I still can't release it in 1.16 I'm not sure if it's my problem ...... QAQ

@ifmissky can you try to capture a new/spawned familiar with a new ring and see if that releases? the fix might not be reotractive for currently captured ones

**Comment by Shibva** [comment] 2021-12-25 21:08
now that makes sence, if some major registry change happens, but it woks fine for me

the only thing that I think coudl be cauisng this issue is with another mod, if this is in a modpack that includes this mod, then theirs a chance that another mod is preventing its release for balancing purposes or something

The only mod that I know that could do this if this is indeed the case is Restriction: Re-Restricted, that MIGHT theoretically be capable of canceling the release function

**Comment by Shibva** [comment] 2021-12-25 21:10
I mean I know I dont have it and I have about 200 mods in the 1.16.5

even though I dont have this issue, I might be able to give you a list on the mods that I have to narrow things down

if this is in fact another mod conflicting with it, then the only way to determine what mod is causing it is to preform the Binary Elimination (AKA Thanos)  Method

**Comment by Dodisosa** [comment] 2021-12-26 08:39
With only this mod active I still get this problem. Playing on 1.16.5 with forge version 1.16.5-forge-36.2.22
Modlist:
curios-forge-1.16.5-4.0.5.3
geckolib-forge-1.16.5-3.0.57
occultism-1.16.5-1.23.7
Patchouli-1.16.4-53.2

I tried summoning a familiar with an egg and also through a ritual, so it was tamed. Made no difference, still couldn't summon it back with the ring.

**Comment by xCalvin2025x** [comment] 2021-12-26 09:44
> Does the soul gem work?

It worked, but the ring didn't
I am in the same environment as Dodisosa
The ring has an NBT tag but cannot be released

Sorry, I hope you can understand
My English bad

**Comment by Dodisosa** [comment] 2021-12-26 10:24
By NBT tag, do mean that the ring show what familiar is in it? Casue I don't get that.

**Comment by Shibva** [comment] 2021-12-26 23:54
ok, NOW I have the issue and I know whats causing it

there seems to be an error with the rings method of caturing it,. for some uknown reason if you capture a familular with it, the data on the ring DOES NOT get tranfered or detects that the faimilular is getting stored into the ring. as a consiquense of this, any enitty that can go into the familular ring will end up being deleted 

its not a issue on relasing them, its an issue on storing them via its entity collection. I had a ring wtih one and it released it just fine, however once I tried to put it back into the ring it didnt come out, and when I looked at the item, I realized that it was empty

This issue is a famulular sotrage issue

**Comment by Shibva** [comment] 2021-12-27 00:00
@klikli-dev so the issue is acutaly being caused by some error in it not storing NBT data on the mob that goes into it, 

@ifmissky and @Dodisosa, If you look closley and know the mod, the ring once you storea  familular should have an addional tooltip added to the item to indicate a familular is being storred in the item, if all you see is the words Slot: Ring after the item name, then that means the ring is empty

as I haev stated aboive, it seems the primary issue is not releasign them (since I was able to with a ring that I had with a dirkwing in it) but it being voided or removed upon capturing it in the ring

this was never an issue before so some recent update might have broken it

if you can @klikli-dev, try to release a hotfix once you locate the issue in the code that would cause it to not record the NBT data of the Entity or whever you do to have an entity being stored into the item because that seems to be the acutal issue here

**Comment by Shibva** [comment] 2021-12-27 00:02
Hope this helps clarify the actual issue at hand ^w^

**Comment by klikli-dev** [comment] 2021-12-27 13:40
Thanks everyone for the research! I'll look into it, I thought that exactly this issue was already resolved (which was different fro m1.18, where it was about releasing, not capturing)  but maybe there was a regression or something I missed

**Comment by xCalvin2025x** [comment] 2021-12-27 16:30
This is a feedback ：It's fixed in the new update, thank you!

**Closed as completed** 2021-12-27 16:36 UTC
Labels: bug, 1.16
