### ISSUE TITLE
Server Time out : LumberJack Minion

### ISSUE THREAD

**Issue by andrey-243** [klikli-dev/occultism#710] opened 2022-05-27 21:35 UTC
In the first place the lumberjack minion seems kindda buggy, stop walk, keep the chest open, do not harvest grown trees in the area work

**To Reproduce**

1. Summon Lumberjack
2. Wait
3. Time out 

Here is my crashlog
[crash-2022-05-27_23.29.22-server.txt](https://github.com/klikli-dev/occultism/files/8789858/crash-2022-05-27_23.29.22-server.txt)

**Comment by klikli-dev** [comment] 2022-05-28 10:04
@lerusse243 this does not seem to be caused by occultism code. The crash log only has 4 occurrences of "occultism" and those are part of the diagnostics for which mods are loaded.

The lumberjack being janky is known and is currently not planned to be fixed (no time to fix / counterbalance the various vanilla AI issues that play into the behaviour here), but it is not known to cause crashes.

Based on the crash log another mod is causing the crash. That does not mean occultism is not at fault: there could be an adverse interaction with how another mod expects occultism entities to behave, but it indicates that *most likely* it can only be fixed on the side of the mod that causes the crash, or with information from that mod author.

What I am seeing a lot in the log is mixins from "enhancedcelestials" and "zombieawareness", it might be a good start to ask in their discords or githubs.

I will close this issue for now, if the authors of those mods require changes on Occultism's side please feel free to open a new issue.

**Closed as completed by klikli-dev** 2022-05-28 10:04 UTC
Labels: bug
