### ISSUE TITLE
[1.19] occultism-common.toml doesn't seem to generate

### ISSUE THREAD

**Issue by jinkhya** [klikli-dev/occultism#811] opened 2022-10-30 23:28 UTC
**Describe the bug**
occultism-common.toml doesn't seem to generate. I was trying to disable oregen.

**To Reproduce**
Make an instance with occultism and its dependencies.
Check config folder

**Expected behavior**
For the file to generate :)

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.47.0
- OS: [e.g. Windows] linux
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: Occultism + dependencies.

**Comment by BlocksterA** [comment] 2022-10-30 23:52
Did you actually run the game to let the config file generate?

**Comment by jinkhya** [comment] 2022-10-30 23:53
yes, I even have a server running, that has restarted a couple times.

**Comment by klikli-dev** [comment] 2022-10-31 08:26
I will look into it, but config files and their auto generation are a forge feature so not sure if I can do much

**Comment by klikli-dev** [comment] 2022-10-31 08:27
Also, ore-gen is not disabled via config any more, forge 1.19 (because minecraft did so too) moved to fully datapack-based worldgen, there are no longer any world gen events that would allow me to check config. You can simply override occcultism worldgen like you would do vanilla ores

**Comment by jinkhya** [comment] 2022-10-31 12:38
If i can do it with datapack that's all good. I didn't think of it. Thank you!

**Comment by klikli-dev** [comment] 2022-11-01 09:30
I just tested with 1.19 occultism + dependencies on the latest version on forge 43.1.1 via curseforge launcher and on start the config files generate as expected in \AppData\Local\Overwolf\Curse\GameInstances\Minecraft\Instances\Occultism 1.19\config, however common config is an empty file, as intended as there are currently no config entries for it.
On some systems the file may not generate at all due to being empty - that would still be expected though. 

Closing this

**Closed as completed by klikli-dev** 2022-11-01 09:30 UTC
Labels: bug
