### ISSUE TITLE
[1.20.4][NeoForge] Crash when trying to create a new world

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1066] opened 2024-02-29 04:22 UTC
**Describe the bug**
Crash when trying to create a new world
I tested with just modonomicon and the game did not crash, so I assume is an Occultism problem. 

**To Reproduce**
1.Try to create a world with:SmartBrainLib-neoforge-1.20.4-1.13.jar, occultism-1.20.4-neoforge-1.116.2.jar, modonomicon-1.20.4-neoforge-1.60.0.jar 
2.Create a new world, and it will crash

**Expected behavior**
A create new world screen should appear

**System (please complete the following information):**
- Modonomicon Version: modonomicon-1.20.4-neoforge-1.60.0.jar 
- OS: Windows
- Minecraft Version: 1.20.4
- Modpack Link and Version, or list of mods: 

**Additional context**
[crash-2024-02-28_23.06.26-client.txt](https://github.com/klikli-dev/modonomicon/files/14442714/crash-2024-02-28_23.06.26-client.txt)

**Comment by klikli-dev** [comment] 2024-02-29 08:08
This is a duplicate of https://github.com/klikli-dev/modonomicon/issues/177 which was fixed in the latest occultism version. If you update it should work :)

**Comment by ffuentesm** [comment] 2024-02-29 13:18
I am in the latest version in 1.20.4. From what I see, only 1.20,1 got a update to work with modonomicon 1.60 
![image](https://github.com/klikli-dev/occultism/assets/44974827/758cc135-0e9c-4753-888e-25316dd57018)

**Comment by klikli-dev** [comment] 2024-02-29 13:39
Apologies, you are correct. The fix was pushed but something went wrong on github, it was not published to CF. Looking into that now

**Comment by klikli-dev** [comment] 2024-02-29 14:03
Found the issue, wrong version format when publishing .. ouch

**Comment by klikli-dev** [comment] 2024-02-29 14:16
1.117.0 is now on CF (might take a bit until it is accessible) which fixes this issue

**Closed as completed by klikli-dev** 2024-02-29 14:16 UTC
Labels: bug
