### ISSUE TITLE
recipe of infused lences in empty in mod's guiding book

### ISSUE THREAD

**Issue by Pliosauroidea** [klikli-dev/occultism#660] opened 2022-02-22 11:36 UTC
**Describe the bug**
I'm playing in 1.16.5 and found the recipe of infused lences seems to be empty in the guiding book.(dictionary of spirits)

**To Reproduce**
1.open the guiding book
2.turn to page ritual : craft infused lenses
3.the recipe shown is empty

**Expected behavior**
there should be a correct recipt(though one can find the recipe via JEI.)

**Screenshots**
otherworld goggles page
![image](https://user-images.githubusercontent.com/37920182/155124933-31729ea2-c6ba-4ba5-ac31-162b13047bfb.png)

crafting recipe page
![image](https://user-images.githubusercontent.com/37920182/155124163-ad8189bb-157e-4055-b424-e28969946d7f.png)

**System (please complete the following information):**
- Occultism Version: 1.16.5-1.23.7
- OS: windows11
- Minecraft Version:1.16.5
- Modpack Link and Version, or list of mods: 
 this mod and reliance
 jei

**Additional context**
none

**Comment by klikli-dev** [comment] 2022-02-22 11:56
Does this issue reproduce if you switch the language to english and reload the save?
This might be an issue with the translation

**Comment by Pliosauroidea** [comment] 2022-02-22 13:21
> Does this issue reproduce if you switch the language to english and reload the save? This might be an issue with the translation

I changed into English(US) and it do turn correct.
![image](https://user-images.githubusercontent.com/37920182/155140451-1e822eb8-56cb-446c-9bf4-485ac0b7c430.png)
so quite likely it's a translation issue.
the bug appears when I use chinese(simplified).

**Comment by klikli-dev** [comment] 2022-02-22 15:49
@Pliosauroidea as translations are community provided, I will close this issue.

@kappa-maintainer in case you are interested in fixing this - the chinese page should probably be compared to the english ones to see if recipe paths match

**Comment by kappa-maintainer** [comment] 2022-02-22 15:56
Confirmed, I will take a look at it.

**Comment by kappa-maintainer** [comment] 2022-02-22 16:09
It was caused by outdated recipe name, no idea how it happened

**Closed as completed** 2022-02-22 16:28 UTC
Labels: bug, 1.16
