### ISSUE TITLE
[BUG]: Dimensional Mineshaft/Miner recipes not working.

### ISSUE THREAD

**Issue by MindBrain27** [klikli-dev/occultism#892] opened 2023-02-07 23:37 UTC
### Bug Description

When looking at uses in JEI for any tier of Miner, it lists the correct (I think) amount of recipes and chances for entries, however both the input and output sides of the recipe are blank. This is not a just JEI issue as when placed in a Dimensional Mineshaft no items are produced but durability is still used.

Custom recipes were added and it worked fine, then this issue occurred after some time. After removing all custom recipes trying to revert things to default the problem still occurs.

### Logs and Crash Reports

https://paste.gemwire.uk/view/e5f27be0

### Screenshots and/or Videos

![mineshaft error](https://user-images.githubusercontent.com/74363414/217387742-9737892a-f0c5-4ad2-92d4-123e45077206.PNG)

### Bug Reproduction

I had previously cleared all recipes using KubeJS and added new ones using datapack recipes, this was fine for weeks until I realized this issue after one of the last few Occultism updates, but not certain which.

I removed all datapack recipes and reverted any changes in KubeJS regarding the Miner. I have created a new world and deleted the old, the issue still persists.

### Expected Behavior

I expect the recipes to show in JEI and be able to obtain them, after I modify them using datapack recipes or KubeJS.

### Minecraft Version

1.19.2

### Mod Version

1.69.0

### Modpack

Other

**Comment by Ciege666** [comment] 2023-02-08 07:19
Confirmed in dev instance, rolled back to 1.68.0 and the renders returned.
![image](https://user-images.githubusercontent.com/30334122/217460857-56b7aee2-c1ef-46af-9b41-9b5fc58c3c4d.png)

**Comment by klikli-dev** [comment] 2023-02-08 07:50
Good find! Looks like some of the recipe changes somehow affected the miner recipes

**Comment by klikli-dev** [comment] 2023-02-08 07:55
Closed in 4afea2c2f0baeafedbbe979c89d2639f1d271c6e, c55dd0c93320aa07045430e3273829eae343aa11, and bddfa8c56ad37526f50b60e34291b47c1f1665d5

**Closed as completed** 2023-02-08 07:57 UTC
Labels: bug
