### ISSUE TITLE
Minecraft crashing at the end of ritual

### ISSUE THREAD

**Issue by VapeTheCalmless** [klikli-dev/occultism#1034] opened 2024-01-19 00:16 UTC
**Describe the bug**
Hello. After trying to summon first ritual spirit (ore crusher) from the book my minecraft crashed and i cannot join this world anymore. I think the problem is in the additional mods that i've been using but im not sure.

**To Reproduce**
1. Ritual starting
2. all items got sucked in
3. And i think right in the moment when the spirit spawns - crashes

**Expected behavior**
To see the spirit

**Screenshots**
Here's the mods i've been using
![Безымянный](https://github.com/klikli-dev/occultism/assets/157071443/873e0d0c-5473-48e1-bbd1-67045d553f75)
mb there is some contradictions?

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.104.1.jar
- OS: 10 windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: screenshot

**Comment by Kevin-Marsh** [comment] 2024-01-19 05:01
Forge version of smartbrainlib used on neoforge does this.

**Comment by klikli-dev** [comment] 2024-01-19 07:22
That's correct.
This issue is a duplicate of https://github.com/klikli-dev/occultism/issues/1029, you can check there for discussions, but as Kevin-Marsh said, simply installing the correct (neo vs forge) version of SBL fixes it :)

**Closed as completed by klikli-dev** 2024-01-19 07:22 UTC
Labels: bug
