### ISSUE TITLE
[1.19.2] Open Storage Accessor cause a crash client 

### ISSUE THREAD

**Issue by LovenKyuu** [klikli-dev/occultism#813] opened 2022-10-31 19:22 UTC
**Describe the bug**

I tried to open the Occultism Storage with the key bind of Storage Accessor and then my client crash without any Crash-report.
My mate tried to open too and he has been crashed.
But the server is Ok, he still working.
Moreover, i've 80% of storage disk used

**To Reproduce**

1. Use your key bind of Storage Accessor
2. Crash

**Expected behavior**

I want to open my Occultism storage without a crash client 

**System (please complete the following information):**
- Occultism Version:  1.19.2-1.46.1
- OS: Windows 10
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods: TNP Limitless 6 1.3.4

**Comment by LovenKyuu** [comment] 2022-10-31 19:26
This is the latest log from server: 

[latest.log](https://github.com/klikli-dev/occultism/files/9904191/latest.log)


And the debug log: 

[debug.log](https://github.com/klikli-dev/occultism/files/9904190/debug.log)

**Comment by klikli-dev** [comment] 2022-11-01 09:22
Does this reproduce in singleplayer too or only multiplayer? @LovenKyuu

**Comment by klikli-dev** [comment] 2022-11-01 09:44
I cannot reproduce this, neither singleplayer nor on a server. 
Can you try if this happens on a minimal pack with only occultism + dependencies in eg curseforge launcher?

**Comment by LovenKyuu** [comment] 2022-11-01 19:44
It's weird because this problem doesn't work all of the time. When it's happend, I kill process from my computer and I go to my server panel to restart it. Then after, Occultism network work nicely until a moment or, for any reason, Client crash

**Comment by klikli-dev** [comment] 2022-11-02 08:55
Is there any way to make it happen for sure? I tried a few times in my dev env, in a minimal occultism back on cf, and with tnp limitless and could not make it happen

**Comment by PoPoGH** [comment] 2022-11-03 15:36
I have a client crash problem also on my side when approaching Dimensional storage in a server on ATM8

**Comment by klikli-dev** [comment] 2022-11-03 15:44
@PoPoGH that is a different issue, see https://github.com/klikli-dev/occultism/issues/816
It is caused by a specific version of Geckolib - by updating to latest Geckolib it will be fixed

**Comment by PoPoGH** [comment] 2022-11-03 15:51
Oh yes sorry :/

**Comment by klikli-dev** [comment] 2022-11-07 11:49
I am closing this for now as inactive, please comment and ping me to reopen if we have more info on how to reproduce it, either with steps on how to do it on a clean install of tnp, or with a specific save you can share

**Closed as completed by klikli-dev** 2022-11-07 11:49 UTC
Labels: bug
