### ISSUE TITLE
A random crash

### ISSUE THREAD

**Issue by Keltas** [klikli-dev/occultism#642] opened 2022-02-01 20:46 UTC
**Describe the bug**
The game crashed randomly after chopping down a tree (menril tree from integrated dynamics). It occured once so far so I don't know if the crash if that was the exact cause of the crash but I've just started out and was chopping trees. I've chopped and replanted a vanilla oak tree, a sun tree from primal magick mod and chopped down without replanting a menril tree from integrated dynamics. The crash log claims it is caused by the beaver familiar tree finding, however I had no chance to get any familiars yet (it occurred literally during the first wood chopping from entering a new world). Upon relogging the game world was fine and no further crashes occurred (as of yet). I am attaching the crash report and the log file in case it is helpful.

**To Reproduce**
I was unable to reproduce it.

**Expected behavior**
Not crashing.

**Screenshots**

**System (please complete the following information):**
- Occultism Version: occultism-1.18.1-1.26.0
- OS: Windows 10
- Minecraft Version: 1.18.1
- Modpack Link and Version, or list of mods:
Custom mod pack with mod list contained within the crash report.

**Additional context**
[crash-2022-02-01_20.25.42-server.txt](https://github.com/klikli-dev/occultism/files/7981757/crash-2022-02-01_20.25.42-server.txt)
[2022-02-01-5.log](https://github.com/klikli-dev/occultism/files/7981805/2022-02-01-5.log)

Edit: I should've checked that it was just reported. Sorry for the second report.

**Comment by klikli-dev** [comment] 2022-02-02 07:20
Thanks for reporting!

Duplicate of #641, handling there

**Closed as completed by klikli-dev** 2022-02-02 07:20 UTC
Labels: bug, duplicate
