### ISSUE TITLE
Crash to desktop when opening dictiorany of spirits

### ISSUE THREAD

**Issue by K1kk0m4n** [klikli-dev/occultism#1025] opened 2024-01-10 12:33 UTC
**Describe the bug**

First game crashed upon opening preview of ritual. Now game crashes even if i attempt to open book.

**To Reproduce**
1. Craft Dictionary of spirits
2. Open book
3. Crash

**Expected behavior**
Book opens and i can read it.

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.100.0
- OS: [e.g. Windows] Windows 11 Home 64
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods:  https://www.curseforge.com/minecraft/modpacks/all-the-mods-9 
Version: 0.2.36

**Additional context**
Crash report of opening book
[crash-2024-01-10_14.18.05-client.txt](https://github.com/klikli-dev/occultism/files/13887663/crash-2024-01-10_14.18.05-client.txt)

Crash report of preview
[crash-2024-01-06_13.53.44-client.txt](https://github.com/klikli-dev/occultism/files/13887658/crash-2024-01-06_13.53.44-client.txt)

**Comment by klikli-dev** [comment] 2024-01-10 13:20
ad preview crash: are you using shaders perchance? 
I got https://github.com/klikli-dev/modonomicon/issues/163 which deals with that (although I am honestly not yet sure how to fix it as I am not familiar with shaders) 

Regarding the full crash now: Looking into it! Meanwhile you can try to update to latest version of modonomicon client-side that might fix it

**Comment by klikli-dev** [comment] 2024-01-10 14:12
Ok so the crash when opening the book does not reproduce for me when using your modonomicon version when I just have occultism + dependencies.

I will test with ATM 9, it could be due to an adverse interaction between mods

**Comment by K1kk0m4n** [comment] 2024-01-10 14:14
Yes i am. Complementary reimagined 5.1.1.
Thx for answer. Keep up great work :)

**Comment by klikli-dev** [comment] 2024-01-10 14:28
Ok so for the preview (once the main crash is out of the way), if you disable the shaders while doing the preview you can use it. As soon as I figure out what is going on I will fix that too of course.

As for the big crash: I cannot get it to reproduce, and it actually indicates that something is wrong during login / world load. So it *may* fix itself by reloading the world or restarting the server.

However i am going to add some workaround code to keep the book from crashing if it happens.
A side effect will be that when you open the book you may not see your book progress - in that case, please close the book and reopen it after a few seconds, then the progress should likely show.

If it does not - then we likely have some mod preventing player data sync, at which point I probably have to talk to the ATM team to figure things out :)

**Comment by K1kk0m4n** [comment] 2024-01-10 14:54
Ok thx again :)

**Comment by klikli-dev** [comment] 2024-01-10 15:48
I am marking this as closed - please ping me if it remains after trying with modonomicon 1.51.1 installed.

Please note that 1.51.1 requires the server to also update, because it needs to request the missing data from the server so that needs the latest version too

**Closed as completed by klikli-dev** 2024-01-10 15:48 UTC
Labels: bug

**Comment by euquinox** [comment] 2024-01-15 17:43
hi! I am not sure if I need to create a separate issue but I am having the same problem, using the latest 1.54.4 version of the mod

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class com.klikli_dev.modonomicon.client.gui.book.BookOverviewScreen cannot be cast to class com.klikli_dev.modonomicon.client.gui.book.BookContentScreen (com.klikli_dev.modonomicon.client.gui.book.BookOverviewScreen and com.klikli_dev.modonomicon.client.gui.book.BookContentScreen are in module modonomicon@1.54.1 of loader 'TRANSFORMER' @615bad16)


[latest.log](https://github.com/klikli-dev/occultism/files/13941616/latest.log)
