### ISSUE TITLE
[BUG]: Dictionary of Spirits rendering issue when FTB Chunks is installed

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#908] opened 2023-03-30 13:38 UTC
### Bug Description

As discussed in Discord. Relevant issues here 
https://github.com/FTBTeam/FTB-Mods-Issues/issues/734
and here
https://github.com/EnigmaticaModpacks/Enigmatica9/issues/286

### Logs and Crash Reports

https://gist.github.com/MuteTiefling/26eb637245e799728c9b64d93d3ab9cb

### Screenshots and/or Videos

With FTB Chunks
![image](https://user-images.githubusercontent.com/9543430/228850251-79229884-effe-4364-8b85-8ed6f20aaa2c.png)

Without FTB Chunks
![image](https://user-images.githubusercontent.com/9543430/228851310-40d9607b-c0db-40e7-928b-ecca32e61198.png)

### Bug Reproduction

Issue is reproducable with limited mod set (JEI, Occultism, FTB Chunks, and all associated library mods)

1. Install Occultism and FTB Chunks
2. Open the Occultism Book
3. Cry
4. Uninstall FTB Chunks (can leave all other mods)
5. Open Occultism Book
6. Smile

### Expected Behavior

Icons to show in book

### Minecraft Version

1.19.2

### Mod Version

occultism-1.19.2-1.73.2

### Modpack

Enigmatica

**Comment by klikli-dev** [comment] 2023-04-01 07:25
See also https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/issues/23

**Comment by klikli-dev** [comment] 2023-04-01 07:40
Closed in https://github.com/klikli-dev/modonomicon/commit/ffa89540dc16f17280d52c6ccac79b4be20653f9

**Closed as completed** 2023-04-01 07:40 UTC
Labels: bug

**Comment by GRCXII** [comment] 2023-04-22 17:43
The icon is normally appeared when chat bar are having display sth , if chat bar is hidden , icon will missing

**Comment by klikli-dev** [comment] 2023-04-23 09:29
@GRCXII please elaborate a bit on what you are referring to?
Is it happening on latest version of modonomicon?
Please provide screenshots or a video so we know what is going on, and maybe open a separate issue for it

**Comment by GRCXII** [comment] 2023-04-26 20:27
> @GRCXII please elaborate a bit on what you are referring to? Is it happening on latest version of modonomicon? Please provide screenshots or a video so we know what is going on, and maybe open a separate issue for it

What i said is the icons in Dictionary of Spirits are missing , it still happening on occultism-1.19.2-1.74.0
I found the icon can be displayed normally when chat bar which in the lower left corner were showing some , but now i cannot reproduce it.
it's weird but i don't know why , the icon sometimes missing or normal display , it looks like random happening and i can't find the regular pattern for that. 
sorry for talking nonsense

**Comment by GRCXII** [comment] 2023-04-26 20:56
@klikli-dev problem solved by using modonomicon-1.19.2-1.30.1,i forgot update modonomicon in modpack.
thanks for your nice work.
