### ISSUE TITLE
Divination Rod multi-target config only re-highlights one instead of all with quick right click

### ISSUE THREAD

**Issue by Dragnier** [klikli-dev/occultism#997] opened 2023-11-22 01:23 UTC
**Describe the bug**
When configured to highlight all found targets, the right click function to re-highlight the last search only does so for one target instead of all targets.

**To Reproduce**
1. Configure setting to allow searching for multiple targets
2. Hold right click on Divination Rod to search
3. See multiple targets
4. Wait for the highlights to go away
5. Quick right click to re-highlight but only get one instead of all

**Expected behavior**
I expected the re-highlight function to show all of the found targets instead of just one.

**Video Link**
https://youtu.be/m3wdO4Mtbmw

**System (please complete the following information):**
- Occultism Version: 1.89.1
- OS: Windows 11
- Minecraft Version: 1.20.1

**Comment by klikli-dev** [comment] 2024-01-14 07:19
This is a valid issue, however the "highlight-all" is not fully supported, it is half a debug feature.
The re-highlight requires to store all found block locations in NBT, storing all these blocks would lead to a huge nbt chunk on the item which is potentially bad (causes issues with storage systems, etc).

So I am going to close this as "working as intended, despite not working optimally"

**Closed as completed by klikli-dev** 2024-01-14 07:19 UTC
Labels: bug
