### ISSUE TITLE
Show Familiar type when stored in a ring

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/occultism#914] opened 2023-04-20 12:52 UTC
**Is your feature request related to a problem? Please describe.**
It's not clear what familiar is stored in a given ring, since it only show's the familiar's name. 

**Describe the solution you'd like**
An extra line in the ring's tooltip showing the familiar's type

**Additional context**
Would be generally helpful for players trying to juggle multiple rings. Would also be nice for custom loot tables so the player knows immediately what is in a ring they might find.

**Comment by klikli-dev** [comment] 2023-04-24 11:46
Seems to be a duplicate of https://github.com/klikli-dev/occultism/issues/907 
Closing this one, #907 seems like something we should implement!

**Closed as completed by klikli-dev** 2023-04-24 11:46 UTC
Labels: duplicate, enhancement
