### ISSUE TITLE
crash when trying to open dimensional storage actuator gui

### ISSUE THREAD

**Issue by theboo** [klikli-dev/occultism#4] opened 2020-05-03 04:18 UTC
**Describe the bug**
crash when opening up dimensional storage actuator
**To Reproduce**
1. Place block 'dimensional storage actuator'
2. Right click to open menu.
3. crash to desktop(is listed as a server crash)
4. See error: https://pastebin.com/q0tmd9HY

**Expected behavior**
GUI should open, i believe? i have never used this item before so not quite sure haha

**System (please complete the following information):**
- Occultism Version: 0.2.2
- OS: windows
- Minecraft Version: 1.15.2
- Modpack Link and Version, or list of mods: occultism, patchouli, jei(all latest versions) and latest forge

**Additional context**
dimensional storage actuator brought in through creative mode as i was testing. I have not tried going through the process of crafting it. But there is a different GUI crash when right clicking on the debug trader as well so i am wondering if it happens in any gui from occultism?

**Comment by klikli-dev** [comment] 2020-05-03 06:29
Thank you for the report, it seems something is off with the reflection helper in published mods - I'll look into it.

**Comment by klikli-dev** [comment] 2020-05-03 07:18
@theboo I moved your report about the spirit trader into a separate issue. The underlying problem was different. Both issues should be fixed in alpha-0.2.3-rev2 (or any release starting at 0.2.3), please let me know if it works for you on those versions once they are on curseforge.

**Comment by theboo** [comment] 2020-05-03 10:11
after updating, i can open the gui, but as soon as i tried to add an item in to the storage i instantly crashed and now when i try to open that same storage i instantly crash again after the guiopens for a half second.

https://pastebin.com/6eGHkKkN

**Comment by klikli-dev** [comment] 2020-05-03 11:36
Good find, thank you! I could not reproduce it in the dev environment, but based on the error it's likely an issue with the obfuscation causing issues with interfaces using vanilla method names. 

Version 0.2.4 should fix this, please let me know if it worked once it's on curse.

**Comment by theboo** [comment] 2020-05-03 12:09
Very cool... I won't be able to playtest this version until I get home from work in about 13hr or so.. But I will for sure! Love this mod so far, super unique and very promising!

**Comment by theboo** [comment] 2020-05-04 01:07
seems to have done the trick! i am able to open the gui again and the items i put in it before crashing are still there. Now to find more game breaking bugs!

**Comment by theboo** [comment] 2020-05-04 01:26
After trying to craft a bound djinni book in the actuator gui(dictonary + djinni book), i instantly crashed to desktop with this crash report:
https://pastebin.com/3CnW7XG8

after reloading the world, opening the same actuator now gives me this crash:
https://pastebin.com/JdFdg6LE

**Closed** 2020-05-04 01:27 UTC
