### ISSUE TITLE
1.19.2 put sometingin the storage system freeze the game for ever

### ISSUE THREAD

**Issue by Gayanfalor** [klikli-dev/occultism#812] opened 2022-10-31 10:02 UTC
**Describe the bug**
Trying to put item in the network now is freezing the game and the game not responding, it was working fine before i got an another remote from lootbags , i put the remote in a chest not linked to the network but it still bug

**To Reproduce**
i dont know if you can reproduce it

**Expected behavior**
to work corectly how it was just before

**Screenshots**
![image](https://user-images.githubusercontent.com/10771109/198982199-ee79cfd5-efb2-4da0-ba1d-6449ea394ac7.png)

**System (please complete the following information):**
- Occultism Version: 1.19.2- 1.46.1
- OS: [e.g. Windows] w10
- Minecraft Version: 1.19.2
- Modpack Link and Version, or list of mods:  TNP limitless 6 1.3.4

**Additional context**
Our network is a bit weird but was working well its a occultism storage linked to a menril network also linked to a ae2 network, they can talk to each other and it was working. i odnt know what made it not working now

**Comment by klikli-dev** [comment] 2022-10-31 10:12
Can you provide logfiles from server and client? 

When you log back into the world, when does it freeze? Right away? Or when you open the storage? 
If it cannot be reproduced independently I would need you to send me your savegame (e.g. via wetransfer) and if you are using a server and it reproduces only in multiplayer, then also your server setup

**Comment by Gayanfalor** [comment] 2022-10-31 10:16
i cant give server as its not mine, here i tried to relink to the matrix and bugged again, if i dont open the storage its not bugging

![image](https://user-images.githubusercontent.com/10771109/198985045-f1429bc0-49ca-4c6a-8b62-fd39a8a0cefb.png)
[latest.log](https://github.com/klikli-dev/occultism/files/9900167/latest.log)

**Comment by klikli-dev** [comment] 2022-10-31 10:18
Thanks for the log - in this case in order to do anything I would need the server log, as the client log does not have the required information.

Without log and without steps to reliably reproduce this my hands are somewhat bound I fear :/ 

Maybe you can send a server moderator or admin a link to this issue so we can talk with them if they can help us figure this out.

**Comment by Gayanfalor** [comment] 2022-10-31 10:19
the admin is my friend he' not here now , i'll say when he get back from work. i'll try to disconnect menril netowrk to see if its maybe from it.

EDIT: even disconnecting menril n etowk does nothing as long as i click on the matrix to open storage it bug

**Comment by klikli-dev** [comment] 2022-10-31 10:43
perfect - give me a ping here when there's more info and I will investigate

**Comment by Gayanfalor** [comment] 2022-10-31 16:05
@klikli-dev  he's here, is there a latest.log too on server? is is the debug.log you want ?

EDIt:  Hmm, now my friend has rebooted the server, and deleted some backup to get some space and now its working :o, hows that possible ? maybe the server was full and could not write occultism info so that why it was bugging ?

**Comment by Gayanfalor** [comment] 2022-10-31 16:20
Hmm, now my friend has rebooted the server, and deleted some backup to get some space and now its working :o, hows that possible ? maybe the server was full and could not write occultism info so that why it was bugging ?

**Comment by klikli-dev** [comment] 2022-10-31 16:39
That might be possible! Occultism storages tend to get rather big due to all the items in there (especially if you have a lot of modded or enchanted items with lots of NBT in there). Generally it is good practice to always keep enough free space on the server and maybe keep the backups offline or in google drive, that way world saves can happen without trouble

Anyway, I will close this for now, please open a new issue if something pops up again!

**Closed as completed by klikli-dev** 2022-10-31 16:39 UTC
Labels: bug
