### ISSUE TITLE
Ores

### ISSUE THREAD

**Issue by wickedsharp** [klikli-dev/occultism#112] opened 2021-01-18 22:41 UTC
**Is your feature request related to a problem? Please describe.**
I couldn't get the foliot crusher ritual to work. Finally realized I was using a silver ore from a different mod (Ice and Fire). Using one freon this mod of course worked. Could you make the ritual work with ores from other mods? 

**Describe the solution you'd like**

**Comment by theboo** [comment] 2021-01-19 04:51
the ritual does work with other mods(for example, anything with the forge:ores/silver tag works in this ritual)... the problem is ice and fire did not properly tag their ores

**Comment by klikli-dev** [comment] 2021-01-19 07:31
Thanks for investigating - closing this here, Ice & Fire will fix this :)

**Closed by klikli-dev** 2021-01-19 07:31 UTC
Labels: enhancement
