### ISSUE TITLE
Datapack issue with JAOPCA

### ISSUE THREAD

**Issue by Irritated-Badger** [klikli-dev/occultism#306] opened 2021-07-23 14:36 UTC
There is a datapack incompatibility between the latest version of Occultism and JAOPCA. I reported it both here and on the other mod's issue tracker. When creating or loading a world the "Datapack loading error"  screen appears. I've narrowed it down to these two mods. 

- Mincraft Version: 1.16.5
- Forge Version: 36.1.61
- Occultism Version: 1.7.0
- JOAPCA Version: 3.4.0.9

**Comment by Rensik** [comment] 2021-07-23 16:21
Can confirm, and JAOPCA doesn't need to be there for it to happen. The "Datapack Loading Error" happens with just Occultism. v1.7.0 and Forge version doesn't matter. I tried several different versions between 36.1.32 and 36.2.0.

**Comment by daniel-eder** [comment] 2021-07-23 18:06
@Rensik thank you for reporting - can you provide the log files?

**Comment by Febilian** [comment] 2021-07-24 04:10
In the interest of getting this figured out more quickly, I did a bit of testing in a standalone instance.

I was unable to reproduce the datapack error screen with nothing but Occultism and its dependencies installed, but as soon as I added in JAOPCA the error began to happen upon trying to create a world.

I would hazard a guess that another mod @Rensik has installed is somehow causing the issue to occur for a similar reason to JAOPCA, but can only speculate on that since I don't know if they have other mods installed/what they are.

Here is the ``latest.log`` from just booting up the game and trying to create a new world:

https://gist.github.com/Febilian/3d86f120b1935ebd1336f229b675343e

``Forge 36.2.0``
``Occultism 1.7.0``
``Curios 1.16.5-4.0.5.2``
``Patchouli 1.16.5-53.1``
``JAOPCA 3.4.0.9``

**Comment by Irritated-Badger** [comment] 2021-07-24 05:26
I work nights and just checked my email, so I do apologize for not getting you the log. If you still need one from me I can get it uploaded in the morning as soon as I get home.

**Comment by klikli-dev** [comment] 2021-07-24 06:17
Thanks guys! Based on the crashlog JAOPCA's occultism compatibility layer has a problem - most likely due to a new setting in the crushing recipes (that's just a guess, but the crash happens in the crushing compat, and there was a change in 1.7.0)

**Comment by klikli-dev** [comment] 2021-07-26 05:29
Will be fixed in the next JAOPCA release, see https://github.com/TheLMiffy1111/JAOPCA/issues/204#issuecomment-886240476

**Closed by klikli-dev** 2021-07-26 05:29 UTC
Labels: bug
