### ISSUE TITLE
Game chrash when opening and closing dictionary of sprits (all the mods 9 No Frills) and when clicking the button to make rituals ingame. 

### ISSUE THREAD

**Issue by OGMakki** [klikli-dev/occultism#1039] opened 2024-01-23 18:50 UTC
**Describe the bug**
I have made a server with my friends, and the game keeps chrashing when i open and close the book. 

**To Reproduce**
1. Opens book
2. looks for what i need 
3. game closes completly and sends me back to launcher.
5. Gets this error message: 
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class com.klikli_dev.modonomicon.client.gui.book.BookOverviewScreen cannot be cast to class com.klikli_dev.modonomicon.client.gui.book.BookContentScreen (com.klikli_dev.modonomicon.client.gui.book.BookOverviewScreen and com.klikli_dev.modonomicon.client.gui.book.BookContentScreen are in module modonomicon@1.54.1 of loader 'TRANSFORMER' @1a7a21d0)

**Expected behavior**
That my game doesn't chrash, and i can read rituals etc. 

**Screenshots**

**System (please complete the following information):**
- Occultism Version: 1.20.1-1.103.0.jar
- OS: [e.g. Windows] Windows 10
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: All the Mods 9 - No Frills0.0.6.zip

**Additional context**

**Comment by klikli-dev** [comment] 2024-01-24 07:35
I cannot reproduce this on No Frills 0.0.9
In fact such a bug has recently been fixed in modonomicon, so likely the No Frills update will fix this for you.
I will close this as fixed, if it still reproduces in 0.0.9 for you please ping me to reopen _and_ provide exact steps (which entries, which links, etc to click) to get the crash

**Comment by OGMakki** [comment] 2024-01-24 18:55
Hey, just updated to 0.0.9 and the issue is still there.. Every time i click the eye on the rituals it says kicks me out of the game?

**Comment by klikli-dev** [comment] 2024-01-25 06:01
@OGMakki on 0.0.9 I can click the eye with no problem and see the preview.
Is it possible that you are using a shaderpack?

Currently some or most of them seem to cause the in-game preview to crash

**Closed as completed** 2024-01-25 06:31 UTC
Labels: bug
