### ISSUE TITLE
White candles don't have a collision box

### ISSUE THREAD

**Issue by Wxrlds** [klikli-dev/occultism#203] opened 2021-03-12 21:58 UTC
**Describe the bug**
The white candle doesn't have a collision box. You can just walk through it.

**To Reproduce**
1. Look straight down and place the white candle
2. You're now inside the candle

**Expected behavior**
The white candle has a collision box/you cannot place the candle while looking straight down

**System (please complete the following information):**
- Occultism Version: occultism-1.16.5-1.0.15
- OS: Windows 10
- Minecraft Version: 1.16.5
- Forge 36.0.54
- curios-forge-1.16.5-4.0.5.0
- Patchouli-1.16.4-50
- jei-1.16.4-7.6.1.71

**Comment by klikli-dev** [comment] 2021-03-13 09:16
This is intended behaviour. The white candle has a collision box (look at it & minecraft will outline it), however just like the torch it is marked as allowing entities to walk through.

**Closed by klikli-dev** 2021-03-13 09:16 UTC
Labels: bug
