### ISSUE TITLE
Otherworld Treese don't drop proper logs when vein mined.

### ISSUE THREAD

**Issue by dorn284** [klikli-dev/occultism#1230] opened 2024-10-23 03:24 UTC
**Describe the bug**
When under the third eye effect, you can't "vein mine" the occult tree and get the correct wood. You get oak wood instead.
Have used Tree Harvester mod, Ars Nouveau Fel tree spell, and Ultimine.

**To Reproduce**
1. Grow Otherworld tree
2. Attempt to vein mine
3. receive normal oak logs

**Expected behavior**
I would expect to receive the other world logs.

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.139.1.jar
- OS: Windows
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: 

**Additional context**
Have eaten the demon dream fruit and the otherworld essence when trying to vein mine. Have not tried using the goggles yet.

**Comment by klikli-dev** [comment] 2024-10-23 16:05
I am not sure if I can fix that on my end. The drop is determined based on the "playerDestroy" function of the block, and there it checks if the player has third eye effect to determine which block it represents (Oak as "hidden" state, or Otherworld wood if "visible")

Presumably the veinminer mods do not simulate this event on each destroyed block to save performance, which leads to Occultism not knowing that third eye is happening. 

However, considering how old this mechanic is, it may now be possible to do the same with a loottable, which *probably* works with veinminers. I will look into that, if not we'll have to work with the veinminer mod makers to find a common solution

**Comment by Eqis-Edu** [comment] 2024-10-23 23:22
I did some tests here, Forge - 47.3.0 and occultism-1.20.1-1.139.1.jar

Works fine
+ ftb-ultimine-forge-2001.1.5.jar 
+ veinmining-forge-1.5.0+1.20.1.jar (standalone enchantment mod)

Don't work and put the wrong sapling
+ treeharvester-1.20.1-9.1.jar 

Strange reactions
+ ars_nouveau-1.20.1-4.12.4-all.jar
The Fell glyph really don't work, but the break glyph (also using AOE) work only with an occultism pickaxe in main hand

The goggles don't matter, only visual

**Comment by klikli-dev** [comment] 2024-10-24 08:24
That result is not too bad to be honest. Ars working with break is interesting because it means the tool is forwarded to the block, but not the player apparently maybe I don't know. But the pickaxe can harvest the logs even without the effect.

**Comment by klikli-dev** [comment] 2024-10-31 09:50
I am closing this for now as it largely behaves as intended. If a change to loot tables is necessary/recommended please reopen and we can check

**Closed as completed by klikli-dev** 2024-10-31 09:50 UTC
Labels: bug
