### ISSUE TITLE
[BUG]: Foliot stuck doesn't move

### ISSUE THREAD

**Issue by Gheim2** [klikli-dev/occultism#891] opened 2023-02-07 22:31 UTC
### Bug Description

Hi, I'm playing All the mods 7 on the sky in a server and the lumberjack foliot doesn't move. it seems stuck. If I place it next to a tree, he breaks it, but he doesn't move and cannot reach the chest. How can i fix it? (The server is hosted by a friend of mine)

### Logs and Crash Reports

No Crash

### Screenshots and/or Videos

https://user-images.githubusercontent.com/87243317/217380784-23e760f5-322e-4657-a66a-7425cc049001.mp4

### Bug Reproduction

1. Be in a Server
2. Spawn a lumberjack
3. Enjoy

### Expected Behavior

I expected the lumberjack to move and destroy all of the trees in an area of 16x16 and put the loot in a chest

### Minecraft Version

1.18.2

### Mod Version

1.63.0

### Modpack

ATM

**Comment by Gheim2** [comment] 2023-02-07 22:37
Little update: also the crusher doesn't move, so i think that all the ai is stuck

**Comment by klikli-dev** [comment] 2023-02-08 07:30
The crusher does not have AI to move it so that is expected.

This issue is known, but there have been two sources in the past:
- in some scenarios the lumberjack's new AI seems to be bugged. I have not been able to reproduce this yet - if you know how to make this happen in an install with just occultism + dependencies please let me know then I might be able to fix it.
- In many cases, especially in modpacks, this has been caused by other mods - usually performance mods, often on the server side only - interfering with AI (it seems these mods stop parts of the AI to save performance, but also cause issues along the way .. )

**Comment by klikli-dev** [comment] 2023-02-17 13:27
@Gheim2 I just got around to testing this with an "out of the box" ATM 7 to the sky server + client I both got from curseforge launcher. 

If I spawn in a sapling and bonemeal it, and then use the lumberjack spirit spawn egg it immediately starts moving to and felling the tree. 

Can you reproduce the issue reliably on a new world with unmodified atm 7? What steps are necessary to make it happen?

**Comment by Gheim2** [comment] 2023-02-17 13:33
@klikli-dev I also tried it in a single player world but it doesn’t have this problem. In a server of atm 7 on the sky it seems to be happening when there are too many entities. Maybe you have to try to reproduce it nearby a vanilla mob grinder. In my server it is nearby it

**Comment by klikli-dev** [comment] 2023-02-17 13:50
@Gheim2 if it is related to too many entities it is either a vanilla issue (unlikely), or some mechanism trying to save performance by turning off entity AI - occultism does not have such a functionality built in, but also cannot prevent other mods from doing so

**Comment by Alrena** [comment] 2023-02-18 22:01
I've had this problem a few times now on a custom built server mod pack. Originally when placing the lumberjack it did nothing, even after messing around with the book for it.
I eventually was able to get it to semi function where it would chop down a tree IF I placed it directly next to the tree and could deposit into a chest placed directly adjacent to it, but it would never move.
The AI only fixed itself fully after a server restart, when it moved for the first time I'd ever seen and started functioning normally.

**Comment by klikli-dev** [comment] 2023-02-19 09:31
@Alrena do you know how to make the bug happen?
In the sense of, starting with just occultism + dependencies, what do I need to do to make it happen (which mods to add, which steps ingame to do)? 

I tried with various modpacks now, singleplayer and dedicated server, and many times just in my dev environment and never had it happen for me

**Comment by Alrena** [comment] 2023-02-21 04:31
I haven't been able to replicate it, and honestly have no idea how it even happened in the first place, sorry. If it ever happens again or I figure out what happened I'll put in an issue here.

**Comment by Tilphor** [comment] 2023-02-27 16:19
I have the same problem on ATM8, unmodified current release and single player world. Janitor works just fine, but Lumberjack exhibits behavior described above.

**Comment by klikli-dev** [comment] 2023-02-28 07:27
@Tilphor Yesterday someone told me the issue for them was related to security craft, but I am not sure if the mere presence of that mod causes it, or if it needs to be set up in some way. I know that mod is present in ATM 8, do you per chance have any of its functionality in use in your world? 

Trying to narrow down where the issue comes from so any info is helpful!

**Comment by squirrelkiller** [comment] 2023-03-01 21:28
Can confirm that this issue reappears in DW20 1.19 pack. The issue seems to be server specific. Single Player has no issues. It does occasionally seem to work though for a single tree here or there.

**Comment by klikli-dev** [comment] 2023-03-12 11:42
@squirrelkiller Occultism 1.19.2-1.72.0 (will be available in a few minutes/hours on CF) adds compatibility for https://www.curseforge.com/minecraft/mc-mods/perviaminvenire. 

It would be worth trying to update occultism and install PerViamInvenire, as it replaces vanilla pathfinding. There is a chance that whatever other mod interferes with navigation, does not do so with PVI (as PVI also contains performance improvements to pathfinding)

**Comment by the-demoncore** [comment] 2023-03-15 00:15
im not using a specific mod pack and just use mods i found that were cool but im having the same issue? though my crusher Does move which is weird since it shouldnt be apparently

**Comment by klikli-dev** [comment] 2023-03-15 07:59
The crusher uses the old vanilla ai and is generally unaffected, the lumberjack uses the new ai (like villagers). 
@the-demoncore if you are on 1.19.2, please try to add the mod linked above and let me know if that helps or not. As the issue does not appear for me it is extremely hard to narrow down where it comes from

**Comment by klikli-dev** [comment] 2023-07-27 13:33
The next update for 1.19.2 and 1.20.1 will introduce a possible fix for this.
Please ping me here to reopen if the issue remains

**Closed as completed** 2023-07-27 13:49 UTC
Labels: bug
