### ISSUE TITLE
[1.21] [Neoforge] Bound items Text unredable

### ISSUE THREAD

**Issue by ffuentesm** [klikli-dev/occultism#1132] opened 2024-06-23 02:01 UTC
**Describe the bug**
Bound items have the entire text scrambled instead of just the orange text

**To Reproduce**
1. hover over a bound item

**Expected behavior**
Only a section of the text should be scrambled

**Screenshots**

https://github.com/klikli-dev/occultism/assets/44974827/f498698b-13e9-4fe9-b94a-1b3be9ad3a98

**System (please complete the following information):**
Occultism Version: 1.133.2
OS: Windows
Minecraft Version: 1.21

**Comment by klikli-dev** [comment] 2024-06-23 06:09
I am not sure I understand (the video is not playing properly for me, so maybe that is why).
To me it looks like the white text is not scrambling? 

I can look into it, but this is all vanilla text effects so I would be surprised if they changed how they work. How does it behave on e.g. 1.20.1?

**Comment by ffuentesm** [comment] 2024-06-23 18:04
in 1.20.1 there is actually no scrambling of the words. All the text is static. 

https://github.com/klikli-dev/occultism/assets/44974827/6eae8ca2-2fea-4705-9d34-14c2f5279b61

**Comment by klikli-dev** [comment] 2024-06-24 04:59
Ok that makes more sense actually, I thought I was going crazy! 
I think I know what is going on, the change from nbt -> data components apparently causes jei to re-roll the name on each tick. I have to look into how to get around that

**Comment by klikli-dev** [comment] 2024-06-24 06:33
@ffuentesm I am wondering, do you have any other mods in the setup?
For me it doesn't do that at all, neither in SP nor in MP. I can try to add something that might help but without reproducing the cause it's a bit of a blind flight :D

**Comment by klikli-dev** [comment] 2024-06-24 06:44
the next commit will auto-close this issue, please ping me to reopen if the released version does not fix it!

**Comment by ffuentesm** [comment] 2024-06-24 11:52
@klikli-dev Yep, I am currently with a few mods in 1.21. I can try to see this without them. 
Your 1.133.3 update, fixed most of the problem. 
Now the only items with the Scrambled text are the 4 mining lamps.

**Comment by ffuentesm** [comment] 2024-06-24 12:00
@klikli-dev the problem persists on the miners even when I have no other mods installed. 
Also, Neoforge 21.0.31 has a new crash on launch
![image](https://github.com/klikli-dev/occultism/assets/44974827/a9c572ec-e708-457f-bf35-f2c0cb691091)

**Comment by klikli-dev** [comment] 2024-06-24 12:03
> @klikli-dev the problem persists on the miners even when I have no other mods installed. Also, Neoforge 21.0.31 has a new crash on launch ![image](https://private-user-images.githubusercontent.com/44974827/342328284-a9c572ec-e708-457f-bf35-f2c0cb691091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzA4NTksIm5iZiI6MTcxOTIzMDU1OSwicGF0aCI6Ii80NDk3NDgyNy8zNDIzMjgyODQtYTljNTcyZWMtZTcwOC00NTdmLWJmMzUtZjJjMGNiNjkxMDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEyMDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZWVlNTAxMWY2YWMxNzMzODI3NjE4Yjg1YTQxYjUxODg1ZDQ1ZjFjYmQwYmQzZGNiZTY2YTI1YjM5NmIzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfXEAFtMAzSPTMGuGfEu2sjOVqkRNQUWTfeEDUPc3zU)

@ffuentesm that crash is due to a breaking change in Neo, the update from 5 minutes ago updates past the breaking changes

**Comment by klikli-dev** [comment] 2024-06-24 12:04
> @klikli-dev the problem persists on the miners even when I have no other mods installed. Also, Neoforge 21.0.31 has a new crash on launch ![image](https://private-user-images.githubusercontent.com/44974827/342328284-a9c572ec-e708-457f-bf35-f2c0cb691091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMzA4NTksIm5iZiI6MTcxOTIzMDU1OSwicGF0aCI6Ii80NDk3NDgyNy8zNDIzMjgyODQtYTljNTcyZWMtZTcwOC00NTdmLWJmMzUtZjJjMGNiNjkxMDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDEyMDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZWVlNTAxMWY2YWMxNzMzODI3NjE4Yjg1YTQxYjUxODg1ZDQ1ZjFjYmQwYmQzZGNiZTY2YTI1YjM5NmIzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VfXEAFtMAzSPTMGuGfEu2sjOVqkRNQUWTfeEDUPc3zU)

@ffuentesm as for the miners, I will quickly test in a live environment if I can make it happen there. 
I think the issue may be the jei version, maybe a newer version causes it and my old one does not or something like that

**Comment by ffuentesm** [comment] 2024-06-24 12:13
From what I am seeing in your commits
You did not add the miners to the Prejenerated Spirit name list unless they are the dimensional_matrix. 
![image](https://github.com/klikli-dev/occultism/assets/44974827/a252387a-6bde-46b2-b65d-8a95c3a17ef0)

**Comment by klikli-dev** [comment] 2024-06-24 12:18
Ahh that must be it. Turned off my brain there for a moment it seems. Let me take a look!

**Comment by klikli-dev** [comment] 2024-06-24 12:28
Ok that should do it! The lamps still didn't reproduce the problem for me, but they are now on the list :)

**Comment by ffuentesm** [comment] 2024-06-24 19:10
Thanks, they are now Fixed.

**Comment by klikli-dev** [comment] 2024-07-03 15:18
Issue exists on EMI still despite being fixed on JEI

**Closed as completed** 2024-07-05 10:14 UTC
Labels: bug
