### ISSUE TITLE
The text goes beyond the page limit.

### ISSUE THREAD

**Issue by Heimdallr-1** [klikli-dev/occultism#919] opened 2023-05-03 13:45 UTC
The text goes beyond the page limit, meaning that it doesn't move to another page and continues down. This problem can be solved similar to what's done in Thaumcraft: if the text is too long, it automatically moves to the next page if possible. Additionally, it's possible to implement page scrolling not only by clicking the mouse button, but also by scrolling the mouse wheel.

**Additional context**
![Снимок экрана (11)](https://user-images.githubusercontent.com/41973639/235934093-002c9907-53ee-47ff-b2bf-1c64af29f445.png)
![Снимок экрана (13)](https://user-images.githubusercontent.com/41973639/235934099-390aab93-ebcf-46cf-a4bf-1280fd03913e.png)

**Comment by klikli-dev** [comment] 2023-05-03 13:59
@Heimdallr-1 that is an issue I have been giving some thought in Modonomicon.
Currently the problem is, that inserting new pages on the fly is not possible due to how the book setup works, as the structure is defined serverside, page overflow however is clientside and depends on the translated texts (it would also confuse links that target a specific page and so on).

Additionally, currently there is no good way to detect such an overflow, until the time it is actually being rendered. 

So I have to find a good solution to this and add it to modonomicon.

I suspect the best solution might be to allow scrolling within the page, but even that is not all that simple, because each page has its own rendering. 

I am very open to suggestions on how to do this from a technical perspective

**Comment by klikli-dev** [comment] 2024-01-14 07:16
Closing this here as it is a modonomicon issue.
In occultism the overflowing texts should be fixed now, if any remain please report them in a new issue.
The scrolling navigation has been added to modonomicon already

**Closed as completed by klikli-dev** 2024-01-14 07:16 UTC
Labels: enhancement
