### ISSUE TITLE
Iesnium ore not highlighted 

### ISSUE THREAD

**Issue by Sz4lka** [klikli-dev/occultism#1125] opened 2024-06-14 10:19 UTC
Hello my friend !
I know a lot of people asking you to help... but i'm also need it :D
Iesnium ore don't highligted. I have the particle effects but that's ... well not making it easyer.
I tryed to place down oak log and nearby a occultism "oak" block, i have particles, but no outline. 
I also downloaded Theurgy.. but still nothing. 

**System (please complete the following information):**
- Occultism Version: occultism-1.20.1-1.131.2.jar
- OS: [e.g. Windows]: Windows 10 
- Minecraft Version: 1.20
- Modpack Link and Version, or list of mods: 

- Alex's Mobs
- AppleSkin
- Arcane Lanterns
- Architectury ApI
- Biomancy
- Biome Spawn point
- BlockUI
- Bookshelf
- Botany Pots
- Botany Trees
- Bountiful
- Caelus API
- Carry On
- Citadel
- Collective
- Comforts
- Construction Wand
- CTD Core
- Curios API
- Domum Ornamentum
- Easy Magic
- Easy Villagers
- Enchantment Descriptions
- Enigmatic Legacy
- Explorer's Compass
- Farmer's Delight
- Fast Leaf Decay
- Flower Doubling
- Forbidden and Arcanus
- Framework
- GeckoLib
- HammerLIB
- Harvest with ease
- Healing Campfire
- Improvable Skills 3
- Jade
- JEI Integration
- JEI
- Just Enough Resources
- Kambrik
- Kotlin for Forge
- KubeJS
- Lootr
- Mighty Mail
- Minecolonies
- Mo' Glowstone
- Mondonomicon
- Moonlight Lib
- Mouse Tweaks
- Mowzie's Mobs
- Multi-Piston
- mutil
- Occultism
- Occultism KubeJS
- Ore Excavation
- Ore Tree:Reborn
- Overflowing Bars
- Patchouli
- Pick Up Notifier
- Polymorph
- Puzzles lib
- Rats
- Rhino
- Sawmill
- SmartBrainLib
- Sons Of Sins
- Sophisticated Backpacks
- Sophisticated Core
- Sophisticated Storage
- Spice of Life : Carrot Edition
- Starter Kit
- Structurize
- Tetra
- The Twilight Forest
- Theurgy
- Time in a bottle
- Time in a bottle Curio Support 
- TownTalk
- Universal Bone Meal
- Valhelsia Core
- Vampirism - Become a vampire!
- Visual Workbench 
- Wool Tweaks
- Xaero's Minimap
- Xaero's World map 

Thanks in advance for your help!

**Comment by klikli-dev** [comment] 2024-06-14 13:55
@Sz4lka when you say "particles" what do you mean?
Does the divination rod get a different color? 
And/Or does a particle "shoot" out of it? 

Also have you tried `useAlternativeDivinationRodRenderer = true` in the occultism client conf file?

**Comment by Sz4lka** [comment] 2024-06-14 14:21
I mean a purple ray.
It does change between white and purple.
And yes sadly i tryed to change this "useAlternativeDivinationRodRenderer = true" but nothing happend

**Comment by Reaviik** [comment] 2024-06-14 15:35
Some players on my server are reporting this problem, when using a divining rod the highlight on Iesnium blocks in the Nether does not appear, while others can see it normally.

**Comment by klikli-dev** [comment] 2024-06-14 15:50
> I mean a purple ray. It does change between white and purple. And yes sadly i tryed to change this "useAlternativeDivinationRodRenderer = true" but nothing happend

That is working as intended. If you see a purple ray moving then it works. The highlight only shows up if the particle rendering does not work. Just follow the ray to the target!


> Some players on my server are reporting this problem, when using a divining rod the highlight on Iesnium blocks in the Nether does not appear, while others can see it normally.

Please refer them to use the `useAlternativeDivinationRodRenderer = true`, they are likely AMD players. 
Alternatively install theurgy, then all of them will get the purple particle effect

**Comment by klikli-dev** [comment] 2024-06-14 15:51
Closing this as intended behaviour (btw: removing theurgy would switch it to use the highlight, without a particle effect. However the highlight may not work on all graphics cards)

**Closed as completed by klikli-dev** 2024-06-14 15:51 UTC
Labels: bug

**Comment by Sz4lka** [comment] 2024-06-15 10:45
Hello my friend!
I sort of fixed my problem :) I configured the scanning range smaller so if the rod is found something it most be ,, near "
Thank you for all your help !
Keep up the good work !
