### ISSUE TITLE
Aviar Circle multiblock preview does not show up.

### ISSUE THREAD

**Issue by BlocksterA** [klikli-dev/occultism#873] opened 2023-01-08 11:48 UTC
Using the latest versions of Occultism and Modonomicon , when clicking on show multiblock preview of Aviars circle it does not show up and when I click a block it says Complete and the bar thing disappears
Edit: others don't and this appears to be an issue with other mods that affect rendering. Here are mods I have that affect rendering (I think):
Alternate current (I don't think this should do anything)
Entity Culling
Flywheel
Iris and Oculus flywheel compat
Oculus
Rubidium
Shimmer

**Comment by klikli-dev** [comment] 2023-01-08 13:36
Checked are not at fault: 
- [x] Alternate current
- [x] Entity Culling
- [x] Flywheel
- [x] Iris and Oculus flywheel compat
- [x] Oculus
- [ ] Rubidium
- [x] Shimmer

**Comment by klikli-dev** [comment] 2023-01-08 14:40
The cause is Rubidum, but considering that they have [144 open issues](https://github.com/Asek3/Rubidium/issues) and a large chunk of them about mod compatibility, I fear there is not a great chance of getting that out of the way.

Closing this here as it is not an occultism/modonomicon issue. Feel free to raise an issue at Rubidum and link back here so they can get in touch with me if they need changes on my end to fix it

**Closed as completed by klikli-dev** 2023-01-08 14:40 UTC
