### ISSUE TITLE
[BUG]: Storage actuator crash

### ISSUE THREAD

**Issue by mrchooch** [klikli-dev/occultism#893] opened 2023-02-11 18:42 UTC
### Bug Description

When opening the storage actuator, the game freezes and eventually crashes

### Logs and Crash Reports

https://paste.gemwire.uk/view/raw/db6ec117

### Bug Reproduction

1. Open Storage Actuator
2. Game Crashes

### Expected Behavior

The game not to crash when I open the storage actuator

### Minecraft Version

1.19.2

### Mod Version

1.67.0

### Modpack

ATM

**Comment by klikli-dev** [comment] 2023-02-11 18:49
Can you please paste the crash log? This seems to be the server log, or a log without crash information.

If the client crashes there should be a separate folder in your minecraft/modpack installation directory that contains crash files 

The most likely reason, though, is that you have an item in the storage actuator that has too much NBT in there

**Comment by mrchooch** [comment] 2023-02-11 18:52
I couldn't find a proper crash log, possibly because the game just freezes when I open the storage, and i then have to force close it through the task manager

Is there anything I can do to remove this item?

**Comment by klikli-dev** [comment] 2023-02-11 19:03
Generally to remove it you'd have to edit the inventory in the world save file with an nbt editor - that works exactly like editing a shulker box. I don't know *how* that works in the sense of which steps/tools are needed from a user perspective though 

That said, the issue i am referring to so far usually produced a crash log (at least the cases reported to me). What happens if you leave the window open for a few minutes, does it ever close on its own? 

Without the info of what exactly is going on that we get from a crashlog it is very hard to assist

**Comment by klikli-dev** [comment] 2023-02-11 19:07
Oh, on another note, if you have any idea which item it could be that you added, it is possible that it can be fixed on the side of the mod that added that item. 

Items with a lot of nbt can be set up by the modder to not send that NBT over network (or rather, only those parts of the nbt data that are necessary to display the item correctly, such as damage to the item). So if we a) know that the issue is due to the nbt and b) can find the mod I can help them set up their items in a safer way

**Comment by mrchooch** [comment] 2023-02-11 20:14
I tried leaving it open for a while but it just stayed frozen.

As far as editing the save file with an nbt editor, do you have any idea what the storage actuator's storage might be listed as within the files?

**Comment by klikli-dev** [comment] 2023-02-12 17:58
I haven't used an nbt editor before so I am not sure. But if you can find a tutorial on how to edit a shulker box (or probably even a normal chest) it should be basically the same

**Comment by klikli-dev** [comment] 2023-02-19 09:32
I am closing this for now as it seems not possible to procure information to fix it. 
If new info pops up that helps to reproduce this please ping me to reopen, or create a new issue

**Closed as completed by klikli-dev** 2023-02-19 09:32 UTC
Labels: bug
